name: compact
theme: terminal
tab_length: 2
wrap: char
reflow: false
table_wrap: fit
heading_layout: flat
smart_indent: false
table_smart_indent: true
hide_comments: true
no_code_language: true
code_guessing: false
code_block_style: simple
callout_style: simple
code_wrap_indent: none
link_style: endtable
link_truncation: tablecut
missing_footnote_style: hide
