use super::*;

impl<'a> EventRenderer<'a> {
    pub(crate) fn new(
        config: &'a Config,
        theme: &'a Theme,
        syntax_set: &'a SyntaxSet,
        code_theme: &'a CodeHighlightTheme,
    ) -> Self {
        Self {
            config,
            theme,
            syntax_set,
            code_theme,
            output: String::new(),
            current_indent: 0,
            blockquote_level: 0,
            blockquote_starts: Vec::new(),
            callout_stack: Vec::new(),
            callout_palette: build_callout_palette(theme),
            list_stack: Vec::new(),
            prepared_list_spacing_elements: VecDeque::new(),
            prepared_blockquote_spacing_elements: VecDeque::new(),
            definition_list_stack: Vec::new(),
            table_state: None,
            pending_html_block_buffer: None,
            link_references: HashMap::new(),
            link_counter: 0,
            current_link_text: String::new(),
            in_link: false,
            paragraph_link_counter: 0,
            paragraph_links: Vec::new(),
            document_links: Vec::new(),
            in_code_block: false,
            code_block_content: String::new(),
            code_block_language: None,
            plaintext_code_block_depth: 0,
            captured_reference_blocks: Vec::new(),
            deferred_reference_blocks: Vec::new(),
            footnote_definitions: Vec::new(),
            footnote_order: Vec::new(),
            current_inline_footnotes: Vec::new(),
            footnote_use_count: HashMap::new(),
            suppress_footnote_output: false,
            footnote_text_state: FootnoteTextState::Idle,
            footnote_text_buffer: String::new(),
            last_header_level: HeadingLevel::H1,
            formatting_stack: Vec::new(),
            active_backtick_style: None,
            current_heading_level: None,
            current_heading_start: None,
            pending_heading_placeholder: None,
            heading_indent: 0,
            content_indent: 0,
            blockquote_indent_stack: Vec::new(),
            smart_level_indents: HashMap::new(),
            prepared_blockquote_smart_indents: VecDeque::new(),
            active_blockquote_smart_indents: Vec::new(),
            current_paragraph_start: None,
            current_paragraph_has_content: false,
            current_paragraph_has_leading_break: false,
            explicit_blank_line_streak: 0,
            pending_task_marker: false,
            pending_task_marker_buffer: String::new(),
            pending_callout_marker: false,
            pending_callout_marker_buffer: String::new(),
            pending_callout_label_override: false,
            pending_callout_label_buffer: String::new(),
            suppress_next_soft_break: false,
            suppress_next_paragraph_break: false,
        }
    }
}
