pub(super) fn command_symbol(name: &str) -> Option<&'static str> {
    if let Some(symbol) = delimiter_symbol(name) {
        return Some(symbol);
    }

    match name {
        "alpha" => Some("α"),
        "beta" => Some("β"),
        "gamma" => Some("γ"),
        "delta" => Some("δ"),
        "epsilon" => Some("ε"),
        "varepsilon" => Some("ϵ"),
        "zeta" => Some("ζ"),
        "eta" => Some("η"),
        "theta" => Some("θ"),
        "vartheta" => Some("ϑ"),
        "iota" => Some("ι"),
        "kappa" => Some("κ"),
        "lambda" => Some("λ"),
        "mu" => Some("μ"),
        "nu" => Some("ν"),
        "xi" => Some("ξ"),
        "pi" => Some("π"),
        "varpi" => Some("ϖ"),
        "rho" => Some("ρ"),
        "varrho" => Some("ϱ"),
        "sigma" => Some("σ"),
        "varsigma" => Some("ς"),
        "tau" => Some("τ"),
        "upsilon" => Some("υ"),
        "phi" => Some("φ"),
        "varphi" => Some("ϕ"),
        "chi" => Some("χ"),
        "psi" => Some("ψ"),
        "omega" => Some("ω"),
        "Alpha" => Some("Α"),
        "Beta" => Some("Β"),
        "Gamma" => Some("Γ"),
        "Delta" => Some("Δ"),
        "Epsilon" => Some("Ε"),
        "Zeta" => Some("Ζ"),
        "Eta" => Some("Η"),
        "Theta" => Some("Θ"),
        "Iota" => Some("Ι"),
        "Kappa" => Some("Κ"),
        "Lambda" => Some("Λ"),
        "Mu" => Some("Μ"),
        "Nu" => Some("Ν"),
        "Xi" => Some("Ξ"),
        "Pi" => Some("Π"),
        "Rho" => Some("Ρ"),
        "Sigma" => Some("Σ"),
        "Tau" => Some("Τ"),
        "Upsilon" => Some("Υ"),
        "Phi" => Some("Φ"),
        "Chi" => Some("Χ"),
        "Psi" => Some("Ψ"),
        "Omega" => Some("Ω"),
        "pm" => Some("±"),
        "mp" => Some("∓"),
        "times" => Some("×"),
        "cdot" => Some("·"),
        "ast" => Some("∗"),
        "star" => Some("⋆"),
        "div" => Some("÷"),
        "neq" | "ne" => Some("≠"),
        "leq" | "le" => Some("≤"),
        "geq" | "ge" => Some("≥"),
        "approx" => Some("≈"),
        "equiv" => Some("≡"),
        "propto" => Some("∝"),
        "sim" => Some("∼"),
        "infty" => Some("∞"),
        "partial" => Some("∂"),
        "nabla" => Some("∇"),
        "angle" => Some("∠"),
        "cdots" => Some("⋯"),
        "ldots" => Some("…"),
        "dots" => Some("…"),
        "vdots" => Some("⋮"),
        "ddots" => Some("⋱"),
        "to" | "rightarrow" => Some("→"),
        "leftarrow" => Some("←"),
        "leftrightarrow" => Some("↔"),
        "Rightarrow" => Some("⇒"),
        "Leftarrow" => Some("⇐"),
        "Leftrightarrow" => Some("⇔"),
        "mapsto" => Some("↦"),
        "in" => Some("∈"),
        "notin" => Some("∉"),
        "subset" => Some("⊂"),
        "subseteq" => Some("⊆"),
        "supset" => Some("⊃"),
        "supseteq" => Some("⊇"),
        "cup" => Some("∪"),
        "cap" => Some("∩"),
        "setminus" => Some("∖"),
        "triangle" => Some("△"),
        "mid" => Some("∣"),
        "forall" => Some("∀"),
        "exists" => Some("∃"),
        "neg" => Some("¬"),
        "land" => Some("∧"),
        "lor" => Some("∨"),
        "top" => Some("⊤"),
        "hbar" => Some("ℏ"),
        _ => None,
    }
}

pub(super) fn delimiter_symbol(name: &str) -> Option<&'static str> {
    match name {
        "(" => Some("("),
        ")" => Some(")"),
        "[" => Some("["),
        "]" => Some("]"),
        "{" => Some("{"),
        "}" => Some("}"),
        "|" => Some("‖"),
        "langle" => Some("⟨"),
        "rangle" => Some("⟩"),
        "lfloor" => Some("⌊"),
        "rfloor" => Some("⌋"),
        "lceil" => Some("⌈"),
        "rceil" => Some("⌉"),
        "lvert" | "vert" => Some("|"),
        "rvert" => Some("|"),
        "lVert" | "Vert" => Some("‖"),
        "rVert" => Some("‖"),
        _ => None,
    }
}

pub(super) fn operator_command(name: &str) -> Option<(&'static str, bool)> {
    match name {
        "sum" => Some(("∑", true)),
        "prod" => Some(("∏", true)),
        "lim" => Some(("lim", true)),
        "arg" => Some(("arg", true)),
        "min" => Some(("min", true)),
        "max" => Some(("max", true)),
        "int" => Some(("∫", false)),
        "iint" => Some(("∬", false)),
        "iiint" => Some(("∭", false)),
        "oint" => Some(("∮", false)),
        "sin" => Some(("sin", false)),
        "cos" => Some(("cos", false)),
        "tan" => Some(("tan", false)),
        "ln" => Some(("ln", false)),
        "log" => Some(("log", false)),
        "exp" => Some(("exp", false)),
        "det" => Some(("det", false)),
        "rank" => Some(("rank", false)),
        "trace" => Some(("trace", false)),
        _ => None,
    }
}

pub(super) fn literal_command(name: &str) -> Option<&'static str> {
    match name {
        "%" => Some("%"),
        "$" => Some("$"),
        "#" => Some("#"),
        "_" => Some("_"),
        "{" => Some("{"),
        "}" => Some("}"),
        "&" => Some("&"),
        "|" => Some("‖"),
        "^" => Some("^"),
        _ => None,
    }
}

pub(super) fn spacing_command(name: &str) -> Option<&'static str> {
    match name {
        "," | ";" | ":" | "!" | " " => Some(" "),
        "quad" => Some("  "),
        "qquad" => Some("    "),
        _ => None,
    }
}

pub(super) fn is_opening_delimiter_command(name: &str) -> bool {
    matches!(name, "langle" | "lceil" | "lfloor" | "lvert" | "lVert")
}

pub(super) fn mathbb_symbol(letter: &str) -> Option<&'static str> {
    match letter {
        "R" => Some("ℝ"),
        "Z" => Some("ℤ"),
        "Q" => Some("ℚ"),
        "C" => Some("ℂ"),
        "N" => Some("ℕ"),
        "P" => Some("ℙ"),
        "E" => Some("𝔼"),
        _ => None,
    }
}
